version: '2'

services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      mynet:
        ipv4_address: 172.25.0.101

  influxdb:
    image: influxdb
    ports: 
      - 8086:8086
    networks:
      mynet:
        ipv4_address: 172.25.0.102

networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24